version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./storage/logs:/app/storage/logs
    user: www-data
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:latest
    environment:
        MYSQL_DATABASE: "${DB_DATABASE}"
        MYSQL_ROOT_USER: "${DB_USERNAME}"
        MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
        -   ./storage/dbdata:/var/lib/mysql
    ports:
        - "33066:3306"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    restart: unless-stopped
    container_name: "oynapp-nginx"
    ports:
      - "${WEBSERVER_PORT}:80"
      - "${WEBSERVER_PORT_SSL}:443"
    volumes:
      - ./:/app
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


